import type { Card } from "memvocado-types";

/** Options for fetching new cards */
export interface GetNewCardsOptions {
  /** Maximum number of new cards to return */
  effectiveLimit: number;
  /**
   * If true: fetch without ordering (limit only, random-ish Firestore behaviour).
   * If false: order by createdAt ASC so oldest cards come first.
   */
  shuffleNewCards: boolean;
}

export interface CardRepository {
  /**
   * Fetch new (firstLearn.isNew === true) cards from a user's deck copy.
   * Respects effectiveLimit and shuffleNewCards ordering.
   */
  getNewCards(
    userId: string,
    deckId: string,
    options: GetNewCardsOptions
  ): Promise<Card[]>;

  /**
   * Fetch due forward cards:
   *   - firstLearn.isFirst === true && firstLearn.isNew === false  (learning phase)
   *   - cardAlgo.due <= end-of-day                                 (FSRS phase)
   */
  getDueCards(userId: string, deckId: string): Promise<Card[]>;

  /**
   * Fetch due reverse cards:
   *   - firstLearnReverse.isFirst === true && firstLearnReverse.isNew === false
   *   - cardAlgoReverse.due <= end-of-day
   */
  getDueReverseCards(userId: string, deckId: string): Promise<Card[]>;

  /**
   * Lazy-init cardAlgoReverse / firstLearnReverse for cards that are missing those
   * fields.  Writes defaults to Firestore via a single batch and mutates the
   * supplied card objects in-place so callers see the updated values immediately.
   */
  initReverseFields(userId: string, deckId: string, cards: Card[]): Promise<void>;

  /** Merge-write a card to Firestore */
  setCard(userId: string, deckId: string, card: Card): Promise<void>;

  /** Get a single card, or null if the document does not exist */
  getCard(userId: string, deckId: string, cardId: string): Promise<Card | null>;

  /** Get a single card from the source deck, or null if not found */
  getSourceDeckCard(deckId: string, cardId: string): Promise<Card | null>;

  /** Get every card in a user's deck copy */
  getAllUserCards(userId: string, deckId: string): Promise<Card[]>;

  /** Get every card in a source (public) deck */
  getAllSourceCards(deckId: string): Promise<Card[]>;

  /**
   * Bulk-copy all cards from a source deck to a user's deck learning copy.
   * Cards are written with firstLearn.isNew = true.
   */
  bulkCopyCards(
    sourceDeckId: string,
    userId: string,
    userDeckId: string
  ): Promise<void>;

  // ── New methods added for deckHandlers refactor ──────────────────────────

  /**
   * Reset all card progress in a user's deck copy.
   * Clears cardAlgo, cardAlgoReverse, firstLearnReverse, lastReviewDate;
   * resets firstLearn to {isNew: true}; and nulls out dailyStats on the deck doc.
   */
  bulkResetCards(userId: string, deckId: string): Promise<void>;

  /**
   * Apply a bulk sync from source deck to user's learning copy.
   * - upsert: new cards to set (with merge)
   * - update: existing cards whose content should be overwritten
   * - delete: card IDs to remove from the user copy
   * - deckUpdate: fields to write back to the user's deck doc (cardsNum, updatedAt)
   * All operations are batched in chunks of 450.
   */
  bulkSyncUserCards(
    userId: string,
    deckId: string,
    ops: {
      upsert: Card[];
      update: Array<{
        id: string;
        cardData: { front: string; back: string };
        tags: string[];
      }>;
      delete: string[];
    },
    deckUpdate: Record<string, unknown>
  ): Promise<void>;

  /**
   * Apply create/update/delete changes to source deck cards (batched in 499-op chunks).
   * - created: new cards (IDs are auto-generated by the repo)
   * - updated: cards whose content changes
   * - deleted: card IDs to delete
   */
  applySourceCardChanges(
    deckId: string,
    changes: {
      created: Array<{
        cardData: { front: string; back: string };
        tags?: string[];
      }>;
      updated: Array<{
        id: string;
        cardData: { front: string; back: string };
        tags?: string[];
      }>;
      deleted: string[];
    }
  ): Promise<void>;

  /**
   * Update a card's content in the source deck.
   * Throws Error("not-found") if the card document does not exist.
   */
  updateSourceCard(
    deckId: string,
    cardId: string,
    data: { cardData: { front: string; back: string }; tags: string[] }
  ): Promise<void>;

  /**
   * Update a card's content in a user's deck copy.
   * No-op if the card document does not exist.
   */
  updateUserCardIfExists(
    userId: string,
    deckId: string,
    cardId: string,
    data: { cardData: { front: string; back: string }; tags: string[] }
  ): Promise<void>;

  /**
   * Paginated fetch of source deck cards.
   * Resolves the startAfterId cursor internally.
   */
  getSourceDeckCardsPaginated(
    deckId: string,
    limit: number,
    startAfterId?: string
  ): Promise<{ cards: Card[]; hasMore: boolean; lastDocId: string | null }>;

  /**
   * Paginated fetch of a user's deck copy cards.
   * Resolves the startAfterId cursor internally.
   */
  getUserDeckCardsPaginated(
    userId: string,
    deckId: string,
    limit: number,
    startAfterId?: string
  ): Promise<{ cards: Card[]; hasMore: boolean; lastDocId: string | null }>;
}
